# Generated by Django 3.0.3 on 2020-02-17 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('ccid', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=50)),
                ('cdes', models.TextField()),
                ('cpic', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mycafe', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('ooid', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('oprice', models.IntegerField()),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cafes.Cafe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('mmid', models.AutoField(primary_key=True, serialize=False)),
                ('mname', models.CharField(max_length=50)),
                ('mpic', models.TextField()),
                ('mtype', models.CharField(max_length=20)),
                ('mprice', models.IntegerField()),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='cafes.Cafe')),
            ],
        ),
    ]
